' PaymentService
@startuml

node PaymentService {
}

node LegacyMonolithApp {
}

cloud PaymentProvider1 {
}

cloud PaymentProvider2 {
}

PaymentService --> PaymentProvider1
PaymentService --> PaymentProvider2
PaymentService --> LegacyMonolithApp

@enduml
